// <auto-generated />
using System;
using ComputerSeekho.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComputerSeekho.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260202165631_annoucement_entity")]
    partial class annoucement_entity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ComputerSeekho.API.Entities.Batch", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("batch_id");

                    b.Property<DateTime?>("BatchEndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("batch_end_date");

                    b.Property<bool>("BatchIsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("batch_is_active");

                    b.Property<string>("BatchLogoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("batch_logo_url");

                    b.Property<string>("BatchName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("batch_name");

                    b.Property<DateTime?>("BatchStartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("batch_start_date");

                    b.Property<decimal?>("CourseFees")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("course_fees");

                    b.Property<DateTime?>("CourseFeesFrom")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("course_fees_from");

                    b.Property<DateTime?>("CourseFeesTo")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("course_fees_to");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("FinalPresentationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("final_presentation_date");

                    b.Property<DateTime?>("PresentationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("presentation_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("BatchId");

                    b.HasIndex("CourseId");

                    b.ToTable("batch_master");
                });

            modelBuilder.Entity("ComputerSeekho.API.Entities.ClosureReason", b =>
                {
                    b.Property<int>("ClosureReasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("closure_reason_id");

                    b.Property<string>("ClosureReasonDesc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("closure_reason_desc");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.HasKey("ClosureReasonId");

                    b.ToTable("closure_reason_master");
                });

            modelBuilder.Entity("ComputerSeekho.API.Entities.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<string>("AgeGrpType")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("age_grp_type");

                    b.Property<string>("CourseDescription")
                        .HasColumnType("TEXT")
                        .HasColumnName("course_description");

                    b.Property<int?>("CourseDuration")
                        .HasColumnType("int")
                        .HasColumnName("course_duration");

                    b.Property<decimal>("CourseFees")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("course_fees");

                    b.Property<DateTime?>("CourseFeesFrom")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("course_fees_from");

                    b.Property<DateTime?>("CourseFeesTo")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("course_fees_to");

                    b.Property<bool>("CourseIsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("course_is_active");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("course_name");

                    b.Property<string>("CourseSyllabus")
                        .HasColumnType("TEXT")
                        .HasColumnName("course_syllabus");

                    b.Property<string>("CoverPhoto")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cover_photo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int?>("VideoId")
                        .HasColumnType("int")
                        .HasColumnName("video_id");

                    b.HasKey("CourseId");

                    b.ToTable("course_master");
                });

            modelBuilder.Entity("ComputerSeekho.API.Entities.Batch", b =>
                {
                    b.HasOne("ComputerSeekho.API.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });
#pragma warning restore 612, 618
        }
    }
}
