// <auto-generated />
using System;
using ComputerSeekho.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComputerSeekho.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ComputerSeekho.API.Entities.Announcement", b =>
                {
                    b.Property<int>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("announcement_id");

                    b.Property<string>("AnnouncementText")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("announcement_text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("valid_from");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("valid_to");

                    b.HasKey("AnnouncementId");

                    b.HasIndex("IsActive");

                    b.HasIndex("ValidFrom", "ValidTo");

                    b.ToTable("announcement_master");
                });

            modelBuilder.Entity("ComputerSeekho.API.Entities.Batch", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("batch_id");

                    b.Property<DateTime?>("BatchEndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("batch_end_date");

                    b.Property<bool>("BatchIsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("batch_is_active");

                    b.Property<string>("BatchLogoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("batch_logo_url");

                    b.Property<string>("BatchName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("batch_name");

                    b.Property<DateTime?>("BatchStartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("batch_start_date");

                    b.Property<decimal?>("CourseFees")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("course_fees");

                    b.Property<DateTime?>("CourseFeesFrom")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("course_fees_from");

                    b.Property<DateTime?>("CourseFeesTo")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("course_fees_to");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("FinalPresentationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("final_presentation_date");

                    b.Property<DateTime?>("PresentationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("presentation_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("BatchId");

                    b.HasIndex("CourseId");

                    b.ToTable("batch_master");
                });

            modelBuilder.Entity("ComputerSeekho.API.Entities.ClosureReason", b =>
                {
                    b.Property<int>("ClosureReasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("closure_reason_id");

                    b.Property<string>("ClosureReasonDesc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("closure_reason_desc");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.HasKey("ClosureReasonId");

                    b.ToTable("closure_reason_master");
                });

            modelBuilder.Entity("ComputerSeekho.API.Entities.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<string>("AgeGrpType")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("age_grp_type");

                    b.Property<string>("CourseDescription")
                        .HasColumnType("TEXT")
                        .HasColumnName("course_description");

                    b.Property<int?>("CourseDuration")
                        .HasColumnType("int")
                        .HasColumnName("course_duration");

                    b.Property<decimal>("CourseFees")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("course_fees");

                    b.Property<DateTime?>("CourseFeesFrom")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("course_fees_from");

                    b.Property<DateTime?>("CourseFeesTo")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("course_fees_to");

                    b.Property<bool>("CourseIsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("course_is_active");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("course_name");

                    b.Property<string>("CourseSyllabus")
                        .HasColumnType("TEXT")
                        .HasColumnName("course_syllabus");

                    b.Property<string>("CoverPhoto")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cover_photo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int?>("VideoId")
                        .HasColumnType("int")
                        .HasColumnName("video_id");

                    b.HasKey("CourseId");

                    b.ToTable("course_master");
                });

            modelBuilder.Entity("ComputerSeekho.API.Entities.Enquiry", b =>
                {
                    b.Property<int>("EnquiryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("enquiry_id");

                    b.Property<int?>("ClosureReasonId")
                        .HasColumnType("int")
                        .HasColumnName("closure_reason_id");

                    b.Property<string>("ClosureReasonText")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("closure_reason");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("EnquirerAddress")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("enquirer_address");

                    b.Property<long?>("EnquirerAlternateMobile")
                        .HasColumnType("bigint")
                        .HasColumnName("enquirer_alternate_mobile");

                    b.Property<string>("EnquirerEmailId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("enquirer_email_id");

                    b.Property<long>("EnquirerMobile")
                        .HasColumnType("bigint")
                        .HasColumnName("enquirer_mobile");

                    b.Property<string>("EnquirerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("enquirer_name");

                    b.Property<string>("EnquirerQuery")
                        .HasColumnType("TEXT")
                        .HasColumnName("enquirer_query");

                    b.Property<DateTime>("EnquiryDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("enquiry_date");

                    b.Property<bool>("EnquiryProcessedFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("enquiry_processed_flag");

                    b.Property<string>("EnquirySource")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("enquiry_source");

                    b.Property<DateTime?>("FollowupDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("followup_date");

                    b.Property<int>("InquiryCounter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("inquiry_counter");

                    b.Property<bool>("IsClosed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_closed");

                    b.Property<string>("SpecialInstructions")
                        .HasColumnType("TEXT")
                        .HasColumnName("special_instructions");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("staff_id");

                    b.Property<string>("StudentName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("student_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("EnquiryId");

                    b.HasIndex("ClosureReasonId");

                    b.HasIndex("CourseId");

                    b.HasIndex("FollowupDate");

                    b.HasIndex("IsClosed");

                    b.HasIndex("StaffId", "IsClosed", "FollowupDate");

                    b.ToTable("enquiry_master");
                });

            modelBuilder.Entity("ComputerSeekho.API.Entities.Placement", b =>
                {
                    b.Property<int>("PlacementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("placement_id");

                    b.Property<int>("BatchId")
                        .HasColumnType("int")
                        .HasColumnName("batch_id");

                    b.Property<int>("RecruiterId")
                        .HasColumnType("int")
                        .HasColumnName("recruiter_id");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("PlacementId");

                    b.HasIndex("BatchId");

                    b.HasIndex("RecruiterId");

                    b.HasIndex("StudentId");

                    b.ToTable("Placements_Master");
                });

            modelBuilder.Entity("ComputerSeekho.API.Entities.Recruiter", b =>
                {
                    b.Property<int>("RecruiterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("recruiter_id");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("logo_url");

                    b.Property<string>("RecruiterName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("recruiter_name");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("status");

                    b.HasKey("RecruiterId");

                    b.ToTable("Recruiter_Master");
                });

            modelBuilder.Entity("ComputerSeekho.API.Entities.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("staff_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("photo_url");

                    b.Property<string>("StaffBio")
                        .HasColumnType("TEXT")
                        .HasColumnName("staff_bio");

                    b.Property<string>("StaffDesignation")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("staff_designation");

                    b.Property<string>("StaffEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("staff_email");

                    b.Property<string>("StaffMobile")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("staff_mobile");

                    b.Property<string>("StaffName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("staff_name");

                    b.Property<string>("StaffPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("staff_password");

                    b.Property<string>("StaffRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("staff_role");

                    b.Property<string>("StaffUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("staff_username");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("StaffId");

                    b.HasIndex("StaffEmail")
                        .IsUnique();

                    b.HasIndex("StaffUsername")
                        .IsUnique();

                    b.ToTable("staff_master");
                });

            modelBuilder.Entity("ComputerSeekho.API.Entities.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<int?>("BatchId")
                        .HasColumnType("int")
                        .HasColumnName("batch_id");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("photo_url");

                    b.Property<int>("RegistrationStatus")
                        .HasColumnType("int")
                        .HasColumnName("registration_status");

                    b.Property<string>("StudentAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("student_address");

                    b.Property<DateTime?>("StudentDob")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("student_dob");

                    b.Property<string>("StudentGender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("student_gender");

                    b.Property<long>("StudentMobile")
                        .HasColumnType("bigint")
                        .HasColumnName("student_mobile");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("student_name");

                    b.Property<string>("StudentPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("student_password");

                    b.Property<string>("StudentQualification")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("student_qualification");

                    b.Property<string>("StudentUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("student_username");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("StudentId");

                    b.HasIndex("BatchId");

                    b.HasIndex("CourseId");

                    b.ToTable("student_master");
                });

            modelBuilder.Entity("ComputerSeekho.API.Entities.Batch", b =>
                {
                    b.HasOne("ComputerSeekho.API.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("ComputerSeekho.API.Entities.Enquiry", b =>
                {
                    b.HasOne("ComputerSeekho.API.Entities.ClosureReason", "ClosureReason")
                        .WithMany()
                        .HasForeignKey("ClosureReasonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ComputerSeekho.API.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ComputerSeekho.API.Entities.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ClosureReason");

                    b.Navigation("Course");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("ComputerSeekho.API.Entities.Placement", b =>
                {
                    b.HasOne("ComputerSeekho.API.Entities.Batch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerSeekho.API.Entities.Recruiter", "Recruiter")
                        .WithMany("Placements")
                        .HasForeignKey("RecruiterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerSeekho.API.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Recruiter");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ComputerSeekho.API.Entities.Student", b =>
                {
                    b.HasOne("ComputerSeekho.API.Entities.Batch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId");

                    b.HasOne("ComputerSeekho.API.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId");

                    b.Navigation("Batch");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("ComputerSeekho.API.Entities.Recruiter", b =>
                {
                    b.Navigation("Placements");
                });
#pragma warning restore 612, 618
        }
    }
}
